### PR TITLE
Support for bondUuid

### PR DESCRIPTION
**Pull request by dxdc**
See: https://github.com/aarons22/homebridge-bond/pull/80

### CODE REVIEW

**Comment by dxdc** [comment]
@aarons22 I made the changes you requested. I had to use a workaround since biguint-format doesn't have a types equivalent.

I absolutely think a retry is needed, from my testing, it does fail sometimes. This package seems reasonable?

https://www.npmjs.com/package/axios-retry

**Comment by dxdc** [comment]
@aarons22 is adding axios-retry still on your radar? :)

**Comment by aarons22** [comment]
@dxdc added here: https://github.com/aarons22/homebridge-bond/pull/92

Seems pretty straight forward?

**Comment by dxdc** [comment]
Looks good @aarons22! Maybe increase the number of retries to 10? I've had 3 fail before. I think the exponential strategy could be OK, will have to test it.

**Comment by chrismerck** [comment]
FWIW, here's how we handle the structure of retries from the Bond Home app:

Retry intervals:  2s, 2s, 3s. --- So the total timeout is 7s after initial request, at which point the user gets error feedback. We've found that most WiFi intermittancies resolve within the 7s, and that most humans are able to tolerate 7s of a (unually non-modal) spinner before it timing out without going nuclear and force-quitting the app thinking it's gotten stuck.

**Comment by dxdc** [comment]
Thanks @chrismerck. That probably works fine for the Bond home app because users are only able to make ~1 request at a time.

I have 20+ Bond devices and when refreshing state, some of them were failing intermittently. I'm using both Node-RED to fetch state as well as the native HomeKit. I could never reproduce these issues using curl directly with the HTTP-based API but it was fairly reliable if I tried to poll 5+ devices from Bond.

It's possible it was related to the requests library; there was a potentially similar issue with node-fetch, so maybe axios will be better: https://github.com/node-fetch/node-fetch/pull/768

I'm in the process of testing the new repo and will update. What are your thoughts on setting up a websocket for communication instead of individual HTTP requests? Could help for things like https://github.com/aarons22/homebridge-bond/issues/81 or situations where maybe one HTTP request succeeds and another fails.

**Comment by chrismerck** [comment]
Websockets don't scale well on the Smart by Bond product.... but, I hear you about the need to slam in a bunch of requests without the overhead of many HTTP connections.

We could open up BPUP for incoming requests... then you could do parallel commands with very little overhead. Downside being that you still need to handle the retries, and we'd need to check on our side that there's enough buffering in the UDP socket to handle ~32 requests at once.

Another option would be, we could support HTTP/1.1 pipelining, or some equivalent proprietary way of putting multiple requests in one connection.

**Comment by aarons22** [comment]
Based on how homebridge polls for updates across accessories, it's going to be difficult to avoid multiple state requests when a single accessory has multiple features.

Here's my current thinking of what I want to do:
- batch/debounce duplicate requests within a small interval (like 100ms) and only execute once. Since the plugin utilizes promises, should be pretty simple to aggregate the promises and execute all of them once the single request comes through. 
- utilize BPUP to listen for changes to state and update homebridge as needed.

**Comment by dxdc** [comment]
@chrismerck @aarons22 sounds like you guys are on it.

> batch/debounce duplicate requests within a small interval (like 100ms)

I like this idea, but maybe it only makes sense to do this for GET/state requests. Reason being, there is already a small delay (~100 ms?) because of the nature of the Bond device/Rf and I'm not sure adding another delay especially when a user directly expects feedback is helpful in all cases.

What about using mqtt, at least for the 'GET' side of things? Doesn't seem like much of a security risk (if that is a concern?). And it would free up the pipeline for only PUT requests, which will be a lot less frequent. That being said, the Bond token is being transmitted in plain text via HTTP so it could easily be sniffed as far as security goes. Note that HAP NodeJS is doing the same thing :)

Not sure what the firmware side looks like, but maybe there is some opportunity to reduce latency there as well (which would in turn make these less of issues). E.g., some kind of queuing system if there isn't one already there.

Just sharing some ideas, appreciate the work here!

**Comment by aarons22** [comment]
I was actually thinking about it a bit further after I responded. If BPUP is implemented, in theory, get requests for state might not be needed (except for maybe the initial state?). Instead of having homebridge poll, the BPUP monitoring would always be pushing the latest and greatest state to homebridge.

**Comment by dxdc** [comment]
^^ That would be excellent. So, the get requests would be ignored?

**Pull request merged**
