### PR TITLE
Retry failed HTTP requests (with Bond-UUID token)

### PR DESCRIPTION
**Pull request by dxdc**
Implementation of the `promise-request-library`, which definitely seems to help with errors. I used 3 retries with a backoff factor of 2 as an initial starting point, but have tweaked it a bit since as even 3 retries didn't help in some cases.

To get this to build properly (as there is no @types/promise-request-retry library), I did the following:

1. Duplicate the `@types/request-promise` library as `@types/promise-request-retry`
2. Replace the `index.d.ts` file with the below code.

I didn't spend the time to write a `@types` module for this, but it does build/run properly.

Now, I can see these kinds of errors in the log:
```log
homebridge-out.log:2020-05-24T16:28:51.409Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices, retry count 3
homebridge-out.log:2020-05-24T16:46:39.980Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/2a2a2a2a2a/state, retry count 3
```

```js
// Type definitions for request-promise-retry

import request = require('request');
import errors = require('./errors');
import Promise = require('bluebird');

declare namespace requestPromise {
    interface RequestPromise<T = any> extends request.Request {
        then: Promise<T>['then'];
        catch: Promise<T>['catch'];
        finally: Promise<T>['finally'];
        cancel: Promise<T>['cancel'];
        promise(): Promise<T>;
    }

    interface RequestPromiseOptions extends request.CoreOptions {
        simple?: boolean;
        retry?: number;
        delay?: number;
        factor?: number;
        verbose_logging?: boolean;
    }

    type RequestPromiseAPI<T= any> = request.RequestAPI<RequestPromise<T>, RequestPromiseOptions, request.RequiredUriUrl>;
    type OptionsWithUri = request.UriOptions & RequestPromiseOptions;
    type OptionsWithUrl = request.UrlOptions & RequestPromiseOptions;
    type Options = OptionsWithUri | OptionsWithUrl;
}

declare const requestPromise: requestPromise.RequestPromiseAPI;
export = requestPromise;

```

### CODE REVIEW

**Comment by aarons22** [comment]
Awesome!

> Replace the index.d.ts file with the below code.

I assume this is just a temporary approach until you validate it's working?

**Comment by dxdc** [comment]
> I assume this is just a temporary approach until you validate it's working?

It is working, but it won't build to `dist` without a `@types` library for this module, so not sure how you want to deal with this. The code I posted is a workaround so you can build/test on your end.

The super weird thing is, I'm getting the *SAME* error regardless of the number of retries! It totally seems that something else going on here.

I built this curl script to rapidly test the HTTP server 10x. No issues whatsoever even after multiple tries. I will try some other approaches to test multithreading but honestly I don't get it.

```sh
#!/bin/sh

# CONFIGURE BOND_IP AND BOND_TOKEN TO MATCH YOUR CONFIGURATION
BOND_IP="192.168.XX.XXX"
BOND_TOKEN="123456789abcdef"

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

BOND_DEVICES=$( curl -s "http://${BOND_IP}/v2/devices" -X GET -d "{\"_token\": \"${BOND_TOKEN}\"}" | jq -r 'keys[]' | grep -v '_' )

while read -r deviceId; do
   deviceName=$( curl -sH "BOND-Token: ${BOND_TOKEN}" "http://${BOND_IP}/v2/devices/${deviceId}" | jq '.name' )
   echo "Trying: $deviceName 5x (${deviceId})"
   for i in {1..10}; do
     echo "${i}: "
     curl -sH "BOND-Token: ${BOND_TOKEN}" "http://${BOND_IP}/v2/devices/${deviceId}/state" | jq
   done
done <<< "${BOND_DEVICES}"
```

**Comment by dxdc** [comment]
@aarons22 you might enjoy the results of my testing. This script runs parallel requests now.

Run it like this:
`bash test_bond_devices.sh | sort`

It runs a request 9 times per each device in parallel. If you're running this on a non-Linux type machine (like a Mac) you may have to install/use `gdate` instead of `date` for %N support.

It will create an output like this:
```log
"All Shades" ("All Shades"}) run #1: ,0 - 183 ms
"All Shades" ("All Shades"}) run #2: ,0 - 192 ms
"All Shades" ("All Shades"}) run #3: ,0 - 190 ms
"All Shades" ("All Shades"}) run #4: ,0 - 119 ms
"All Shades" ("All Shades"}) run #5: ,0 - 193 ms
"All Shades" ("All Shades"}) run #6: ,0 - 190 ms
"All Shades" ("All Shades"}) run #7: ,0 - 149 ms
"All Shades" ("All Shades"}) run #8: ,0 - 243 ms
"All Shades" ("All Shades"}) run #9: ,0 - 143 ms
```

Strangely, I'm not seeing a problem here. Impressively, after testing 19 devices (multiple times), I'm getting average response times of ~300-500 +/- 400 ms (std. deviation) and a maximum response time of 1300-1500 ms. The retries I listed should be more than sufficient?

```sh
#!/bin/bash

# CONFIGURE BOND_IP AND BOND_TOKEN TO MATCH YOUR CONFIGURATION
BOND_IP="192.168.XX.XXX"
BOND_TOKEN="123456789abcdef"

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

BOND_DEVICES=$( curl -s "http://${BOND_IP}/v2/devices" -X GET -d "{\"_token\": \"${BOND_TOKEN}\"}" | jq -r 'keys[]' | grep -v '_' )

while read -r deviceId; do
   deviceName=$( curl -sH "BOND-Token: ${BOND_TOKEN}" "http://${BOND_IP}/v2/devices/${deviceId}" | jq '.name' )
   for i in {1..9}; do
    (
        start=$( date +%s%N )
        STATE=$( curl -sH "BOND-Token: ${BOND_TOKEN}" "http://${BOND_IP}/v2/devices/${deviceId}/state" | jq -r '[.power, .open]|@csv' )
        echo "$deviceName ($deviceName}) run #${i}: ${STATE} - $((($(date +%s%N) - $start)/1000000)) ms"

    ) &
   done
done <<< "${BOND_DEVICES}"
```

**Comment by aarons22** [comment]
I just noticed something locally. It looks like the plugin might be making the same request several times in a row, which might the reason you're seeing failed requests. 

You seeing anything like this?

```
[5/24/2020, 2:30:49 PM] [Bond] Adding accessory Living Room LR Fan
[5/24/2020, 2:30:49 PM] [Bond] DEBUG: [Ceiling Fan] min step: 33, max value: 99
[5/24/2020, 2:30:49 PM] [Bond] DEBUG: Request [get http://192.168.200.14/v2/devices/3347bad1/state] - body: {}
[5/24/2020, 2:30:49 PM] [Bond] DEBUG: Request [get http://192.168.200.14/v2/devices/3347bad1/state] - body: {}
[5/24/2020, 2:30:49 PM] [Bond] DEBUG: Request [get http://192.168.200.14/v2/devices/3347bad1/state] - body: {}
```

**Comment by dxdc** [comment]
I think you're right @aarons22. Strangely, it seems to only happen with certain devices for me. I don't have DEBUG enabled, but have a look at these logs:

```log
2020-05-24T18:49:55.139Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/2a2a2a2a/state, retry count 5
2020-05-24T18:49:57.377Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/2a2a2a2a/state, retry count 4
2020-05-24T18:49:59.797Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/2a2a2a2a/state, retry count 3
[5/24/2020, 1:50:01 PM] [Bond] got value: false
```

Interestingly, it seems the final request does receive the value. I have multiple examples like this in the log.

**Comment by aarons22** [comment]
After I get done updating dependencies I’ll see if I can prevent so many requests. It’s likely accessories who have multiple devices trying to get the latest state for the device. For example, a fan that has a light and dimmer will request state for each of those services.

**Comment by dxdc** [comment]
@aarons22 I pushed a few more commits so it builds/compiles properly (and, fixed the comparison to `{}` in the code).

While I confirmed this is true:
> It’s likely accessories who have multiple devices trying to get the latest state for the device.

It is unfortunately not the culprit. I found an isolated case of this that had no hb activity for the prior 4 minutes except a single state request. I'm thinking at this point it's either: 1) some kind of weird issue with the `request` library / Bond firmware or 2) Bond firmware itself. I can't reproduce this at all with curl.

Maybe the Bond webserver should be forcibly closing the connection (if it's not already)? There seemed to be a related issue with node-fetch that was fixed *very* recently:

https://github.com/node-fetch/node-fetch/issues/309
https://github.com/node-fetch/node-fetch/commit/63d366346695d95d8a91af39ddf9c92c8c226ad0

Here's an example where just a single state request failed:

```
1|homebridge      | [5/25/2020, 1:59:11 PM] [Bond] DEBUG: Request [GET http://192.168.XX.XX/v2/devices/2a2a2a2a/state] - body: {}
1|homebridge      | 2020-05-25T18:59:13.114Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/2a2a2a2a/state, retry count 5
1|homebridge      | 2020-05-25T18:59:15.343Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/2a2a2a2a/state, retry count 4
1|homebridge      | 2020-05-25T18:59:17.756Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/2a2a2a2a/state, retry count 3
1|homebridge      | [5/25/2020, 1:59:19 PM] [Bond] DEBUG: Response [GET http://192.168.XX.XX/v2/devices/2a2a2a2a/state] - {"power":0,"_":"b498f203"}
1|homebridge      | [5/25/2020, 1:59:19 PM] [Bond] got value: false
```

Here's an example where multiple failed. Note that I changed the timeout in BondApi.ts to 1000 (vs. 10000) in case that was too long.

```
1|homebridge  | [5/25/2020, 4:02:55 PM] [Bond] DEBUG: Request [GET http://192.168.XX.XX/v2/devices/xxxxxx46/state]
1|homebridge  | [5/25/2020, 4:02:55 PM] [Bond] DEBUG: Request [GET http://192.168.XX.XX/v2/devices/xxxxxxc4/state]
1|homebridge  | [5/25/2020, 4:02:55 PM] [Bond] DEBUG: Request [GET http://192.168.XX.XX/v2/devices/xxxxxxc7/state]
1|homebridge  | [5/25/2020, 4:02:55 PM] [Bond] DEBUG: Request [GET http://192.168.XX.XX/v2/devices/xxxxxxc8/state]
1|homebridge  | 2020-05-25T21:02:56.511Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxx46/state, retry count 5
1|homebridge  | 2020-05-25T21:02:56.520Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc4/state, retry count 5
1|homebridge  | 2020-05-25T21:02:56.522Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc7/state, retry count 5
1|homebridge  | 2020-05-25T21:02:56.523Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc8/state, retry count 5
1|homebridge  | 2020-05-25T21:02:57.628Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxx46/state, retry count 4
1|homebridge  | 2020-05-25T21:02:57.655Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc4/state, retry count 4
1|homebridge  | 2020-05-25T21:02:57.657Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc7/state, retry count 4
1|homebridge  | 2020-05-25T21:02:57.660Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc8/state, retry count 4
1|homebridge  | 2020-05-25T21:02:58.739Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxx46/state, retry count 3
1|homebridge  | 2020-05-25T21:02:58.765Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc4/state, retry count 3
1|homebridge  | 2020-05-25T21:02:58.777Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc7/state, retry count 3
1|homebridge  | 2020-05-25T21:02:58.779Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc8/state, retry count 3
1|homebridge  | 2020-05-25T21:02:59.851Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxx46/state, retry count 2
1|homebridge  | 2020-05-25T21:02:59.878Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc4/state, retry count 2
1|homebridge  | 2020-05-25T21:02:59.918Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc7/state, retry count 2
1|homebridge  | 2020-05-25T21:02:59.921Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc8/state, retry count 2
1|homebridge  | 2020-05-25T21:03:00.960Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxx46/state, retry count 1
1|homebridge  | [5/25/2020, 4:03:00 PM] [Bond] DEBUG: Error [GET http://192.168.XX.XX/v2/devices/xxxxxx46/state] - {"name":"RequestError","message":"Error: ETIMEDOUT","cause":{"code":"ETIMEDOUT","connect":true},"error":{"code":"ETIMEDOUT","connect":true},"options":{"method":"GET","uri":"http://192.168.XX.XX/v2/devices/xxxxxx46/state","headers":{"BOND-Token":"XXX"},"body":{},"json":true,"simple":false,"timeout":1000,"resolveWithFullResponse":false,"transform2xxOnly":false},"accepted":false}
1|homebridge  | [5/25/2020, 4:03:00 PM] [Bond] A request error occurred: Error: ETIMEDOUT
1|homebridge  | [5/25/2020, 4:03:00 PM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
1|homebridge  | 2020-05-25T21:03:01.008Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc4/state, retry count 1
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] DEBUG: Error [GET http://192.168.XX.XX/v2/devices/xxxxxxc4/state] - {"name":"RequestError","message":"Error: ETIMEDOUT","cause":{"code":"ETIMEDOUT","connect":true},"error":{"code":"ETIMEDOUT","connect":true},"options":{"method":"GET","uri":"http://192.168.XX.XX/v2/devices/xxxxxxc4/state","headers":{"BOND-Token":"XXX"},"body":{},"json":true,"simple":false,"timeout":1000,"resolveWithFullResponse":false,"transform2xxOnly":false},"accepted":false}
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] A request error occurred: Error: ETIMEDOUT
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
1|homebridge  | 2020-05-25T21:03:01.063Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc7/state, retry count 1
1|homebridge  | 2020-05-25T21:03:01.069Z - info: [request-promise-retry] Encountered error Error: ETIMEDOUT for GET request to http://192.168.XX.XX/v2/devices/xxxxxxc8/state, retry count 1
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] DEBUG: Error [GET http://192.168.XX.XX/v2/devices/xxxxxxc7/state] - {"name":"RequestError","message":"Error: ETIMEDOUT","cause":{"code":"ETIMEDOUT","connect":true},"error":{"code":"ETIMEDOUT","connect":true},"options":{"method":"GET","uri":"http://192.168.XX.XX/v2/devices/xxxxxxc7/state","headers":{"BOND-Token":"XXX"},"body":{},"json":true,"simple":false,"timeout":1000,"resolveWithFullResponse":false,"transform2xxOnly":false},"accepted":false}
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] A request error occurred: Error: ETIMEDOUT
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] DEBUG: Error [GET http://192.168.XX.XX/v2/devices/xxxxxxc8/state] - {"name":"RequestError","message":"Error: ETIMEDOUT","cause":{"code":"ETIMEDOUT","connect":true},"error":{"code":"ETIMEDOUT","connect":true},"options":{"method":"GET","uri":"http://192.168.XX.XX/v2/devices/xxxxxxc8/state","headers":{"BOND-Token":"XXX"},"body":{},"json":true,"simple":false,"timeout":1000,"resolveWithFullResponse":false,"transform2xxOnly":false},"accepted":false}
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] A request error occurred: Error: ETIMEDOUT
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] DEBUG: Request [GET http://192.168.XX.XX/v2/devices/xxxxxxc4/state]
1|homebridge  | [5/25/2020, 4:03:01 PM] [Bond] DEBUG: Request [GET http://192.168.XX.XX/v2/devices/xxxxxxc4/state]

```

**Comment by dxdc** [comment]
@aarons22 The above still being true, I tweaked the retry settings and now it seems behaved for now on my end (at least for the past 12 hours). I still feel these timeouts should not be happening, but with the latest changes it seems to be working smoothly.

**Comment by chrismerck** [comment]
AFAICT this PR effects only GET requests, right? If I'm wrong and this also impacts the PUT action requests, then you may want to implement the request id feature.

As you are probably already aware, there's a trick to retrying non-idempotent request (such as PUT action): care must be taken to avoid duplicate actions. This is especially a problem with toggle lights as the second request would actually defeat the purpose of the first! The trick is to use the same request id (`Bond-UUID` HTTP header) for the retried requests. The Bond firmware will not take action a second time, but rather return you a cached response.

To do this, for every request you should generate an unsigned 64-bit integer (the "request id") , forcing the most-significant byte to be 0x18 (which we have reserved for HomeBridge) and then add it to a `Bond-UUID` HTTP header in lower-case hex with leading zeros. In C you can use `PRIx64`. The header looks like this:

`Bond-UUID: 1811223344aabbccdd`

If you need to retry the same request, then use the same request id.

**Comment by dxdc** [comment]
@chrismerck Good point!

I wasn't aware of the `Bond-UUID` header, but it makes good sense. Actually, the retry was affecting both GET and PUT requests, but rather than change the number of retries based on the request, I think it makes sense to implement this change.

I made the changes in the latest commit, which seem to be working on my end: 1008952

**Comment by dxdc** [comment]
Thanks @chrismerck, I had implemented based on the length you provided:

> Bond-UUID: 1811223344aabbccdd

I read over the docs for `flake-idgen` (see https://github.com/T-PWK/flake-idgen).

image

Because the worker/datacenter are both = 0 as default, if we just remove these bits we should be OK! While I agree the chance of a uuid conflict is very low for your JS library, it is non-zero, where as for this library it would throw an exception. I amended the PR with this change.

Btw, just to doubly-convince myself of this, I tried it a few times:

```js
const FlakeId = require('flake-idgen');
const intformat = require('biguint-format');
const flakeIdGen = new FlakeId();

let i;

for (i = 0; i < 50000000; i++) {
  const uuid = intformat(flakeIdGen.next(), 'hex', { prefix: '18', padstr: '0', size: 16 });
  testZero = uuid.substring(13, 15) == '00';
  if (testZero) continue;

  // bondUuid = uuid.substring(0, 13) + uuid.substring(15, 18);
  console.log ('ERROR!! ' + uuid + '\n');
}
```

**Comment by chrismerck** [comment]
> I had implemented based on the length you provided:

That's what I get for not documenting and getting an internal PR before I share things 🤦   sorry for that!

Anyways, it seems that you have robust retry and are leveraging our de-duplication trick. Awesome!

**Comment by aarons22** [comment]
@dxdc I just finished refactoring several parts of the project, including dropping `request` in favor of `axios` (you can see the full list of changes [here](https://github.com/aarons22/homebridge-bond/pull/82)).

At this point, it looks like the main change for this PR is the `Bond-UUID` header, which I’d love to get merged. Can you rebase your changes on master? Seems like most of this PR is just linting, which has been updated anyways, so I’d prefer to have those changes dropped.

As for the retry logic - do you think this is still needed? There isn’t built in retry functionality in axios but I did some googling and it sounds like you can use [interceptors](https://github.com/axios/axios/issues/934#issuecomment-515203792).

**Pull request closed without merging**
